'use client';
import {useState} from 'react';
import {createBrowserClient} from '@supabase/ssr';
import {authUrl,authKey} from '@/lib/auth/config';
export default function CustomerAuth({done}:{done:()=>void}) {
 const [register,setRegister]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const client=()=>createBrowserClient(authUrl,authKey);
 async function google(){setBusy(true);setMessage('');try { const response=await fetch(authUrl+'/auth/v1/settings',{headers:{apikey:authKey}});const settings=await response.json() as {external?:{google?:boolean}};if(!response.ok || !settings.external?.google){setMessage('Login Google sedang disiapkan. Silakan gunakan email.');setBusy(false);return;} } catch {setMessage('Koneksi belum tersedia. Silakan coba lagi.');setBusy(false);return;}const {error}=await client().auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+'/auth/callback'}});if(error){setMessage('Login Google belum tersedia. Gunakan email atau hubungi tim KLIKFIBER.');setBusy(false);}}
 return <div className="customer-auth"><div className="auth-toggle"><button type="button" aria-pressed={!register} onClick={()=>setRegister(false)}>Masuk</button><button type="button" aria-pressed={register} onClick={()=>setRegister(true)}>Daftar</button></div><button className="btn outline" disabled={busy} onClick={google}>Lanjutkan dengan Google</button><p className="auth-divider">atau gunakan email</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');try{const {data,error}=register?await client().auth.signUp({email,password,options:{emailRedirectTo:location.origin+'/auth/callback'}}):await client().auth.signInWithPassword({email,password});if(error)throw error;if(data.session){done();}else setMessage('Periksa email Anda untuk mengonfirmasi pendaftaran.');}catch{setMessage('Belum berhasil. Periksa email dan kata sandi, atau coba beberapa saat lagi.');}finally{setBusy(false);}}}><label>Email<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Kata sandi<input type="password" minLength={8} required autoComplete={register?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)}/></label><button className="btn" disabled={busy}>{busy?'Memproses…':register?'Buat akun':'Masuk'}</button></form>{message&&<p role="status">{message}</p>}<p className="small muted">Dengan melanjutkan, Anda menyetujui <a href="/syarat">Syarat & Ketentuan</a> dan <a href="/privasi">Kebijakan Privasi</a>.</p></div>;
}
